-- ============================================================
-- Dynamic Resume All Tasks and Dynamic Tables
-- Generated on: 2025-01-27
-- ============================================================
--
-- OVERVIEW:
-- This script dynamically discovers all suspended tasks and dynamic tables
-- in the AAA_DEV_SYNTHETIC_BANK database and resumes them automatically.
-- It uses a hybrid approach: discovery + known objects for reliability.
--
-- BUSINESS PURPOSE:
-- - Restart all automated processes after maintenance
-- - Resume data processing workflows
-- - Restore system to operational state
-- - Re-enable all data aggregation and reporting
--
-- USAGE:
-- 1. Execute this script to resume all suspended tasks and DTs
-- 2. System will return to normal operational state
-- 3. All dynamic tables will begin refreshing automatically
--
-- SAFETY FEATURES:
-- - Only affects AAA_DEV_SYNTHETIC_BANK database
-- - Preserves all object definitions
-- - Can be safely re-executed
-- - Logs all operations for audit trail
-- ============================================================

USE DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- DISCOVER SUSPENDED TASKS AND DYNAMIC TABLES
-- ============================================================
SELECT 'Discovering suspended tasks and dynamic tables...' AS status;

-- Show all tasks (for information)
SHOW TASKS IN DATABASE AAA_DEV_SYNTHETIC_BANK;

-- Show all dynamic tables (for information)
SHOW DYNAMIC TABLES IN DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- RESUME ALL DYNAMIC TABLES (59 total across all schemas)
-- ============================================================
SELECT 'Resuming dynamic tables...' AS status;

-- Resume REP_AGG_001 Dynamic Tables (Core Reporting - 9 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CUSTOMER_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_ANOMALY_ANALYSIS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_HIGH_RISK_PATTERNS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_SETTLEMENT_ANALYSIS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LIFECYCLE_ANOMALIES RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Equity - 4 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_POSITIONS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_CURRENCY_EXPOSURE RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_HIGH_VALUE_EQUITY_TRADES RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Credit Risk - 5 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_CUSTOMER_RATINGS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_PORTFOLIO_METRICS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CUSTOMER_RATING_HISTORY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_RWA_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_RISK_TRENDS RESUME;

-- Resume REP_AGG_001 Dynamic Tables (FRTB - 4 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_RISK_POSITIONS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_SENSITIVITIES RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_CAPITAL_CHARGES RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_NMRF_ANALYSIS RESUME;

-- Resume REP_AGG_001 Dynamic Tables (BCBS 239 - 6 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_AGGREGATION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_EXECUTIVE_DASHBOARD RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_REGULATORY_REPORTING RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_CONCENTRATION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_LIMITS RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_DATA_QUALITY RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Portfolio - 1 table)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_PORTFOLIO_PERFORMANCE RESUME;

-- Resume CRM_AGG_001 Dynamic Tables (11 tables: 7 CRM + 1 Account + 3 Employee Analytics)
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_ADDRESSES_CURRENT RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_ADDRESSES_HISTORY RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_CURRENT RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_HISTORY RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_LIFECYCLE RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_360 RESUME;

-- Resume Account Aggregation (1 table in CRM_AGG_001)
ALTER DYNAMIC TABLE CRM_AGG_001.ACCA_AGG_DT_ACCOUNTS RESUME;

-- Resume Employee Analytics (3 tables in CRM_AGG_001)
ALTER DYNAMIC TABLE CRM_AGG_001.EMPA_AGG_DT_ADVISOR_PERFORMANCE RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.EMPA_AGG_DT_TEAM_LEADER_DASHBOARD RESUME;
ALTER DYNAMIC TABLE CRM_AGG_001.EMPA_AGG_DT_PORTFOLIO_BY_ADVISOR RESUME;

-- Resume REF_AGG_001 Dynamic Tables (1 table)
ALTER DYNAMIC TABLE REF_AGG_001.REFA_AGG_DT_FX_RATES_ENHANCED RESUME;

-- Resume PAY_AGG_001 Dynamic Tables (6 tables)
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_TRANSACTION_ANOMALIES RESUME;
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_ACCOUNT_BALANCES RESUME;
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_CUSTOMER_TRANSACTION_SUMMARY RESUME;
ALTER DYNAMIC TABLE PAY_AGG_001.ICGA_AGG_DT_SWIFT_PACS008 RESUME;
ALTER DYNAMIC TABLE PAY_AGG_001.ICGA_AGG_DT_SWIFT_PACS002 RESUME;
ALTER DYNAMIC TABLE PAY_AGG_001.ICGA_AGG_DT_SWIFT_PAYMENT_LIFECYCLE RESUME;

-- Resume EQT_AGG_001 Dynamic Tables (3 tables)
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_CUSTOMER_ACTIVITY RESUME;

-- Resume FII_AGG_001 Dynamic Tables (5 tables)
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_DURATION_ANALYSIS RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_CREDIT_EXPOSURE RESUME;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_YIELD_CURVE RESUME;

-- Resume CMD_AGG_001 Dynamic Tables (5 tables)
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_TRADE_SUMMARY RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_PORTFOLIO_POSITIONS RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_DELTA_EXPOSURE RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_VOLATILITY_ANALYSIS RESUME;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_DELIVERY_SCHEDULE RESUME;

-- Resume REP_AGG_001 Dynamic Tables (LCR - 6 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_HQLA RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_OUTFLOW RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_HQLA_CALCULATION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_OUTFLOW_CALCULATION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_DAILY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_TREND RESUME;

-- Resume REP_AGG_001 Dynamic Tables (Loan Portfolio - 5 tables)
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_PORTFOLIO_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_LTV_DISTRIBUTION RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_APPLICATION_FUNNEL RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_AFFORDABILITY_SUMMARY RESUME;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_CUSTOMER_LOAN_SUMMARY RESUME;


-- ============================================================
-- RESUME ALL TASKS (34 total: 18 load tasks + 15 cleanup tasks + 1 DocAI root task)
-- ============================================================
-- IMPORTANT: Child tasks must be resumed BEFORE parent tasks!
SELECT 'Resuming tasks...' AS status;

-- ============================================================
-- Resume CRM_RAW_001 Tasks (13 tasks: 7 load + 6 cleanup)
-- ============================================================
-- Resume child tasks before parent tasks
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_CUSTOMERS RESUME;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_CUSTOMERS RESUME;

ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ADDRESSES RESUME;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_ADDRESSES RESUME;

ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EXPOSED_PERSON RESUME;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_EXPOSED_PERSON RESUME;

ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_CUSTOMER_STATUS RESUME;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_CUSTOMER_EVENTS RESUME;

ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EMPLOYEES RESUME;
ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_LOAD_EMPLOYEES RESUME;

ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ASSIGNMENTS RESUME;
ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_LOAD_ASSIGNMENTS RESUME;

-- Resume ACC_RAW_001 Tasks (1 task) - Task is in CRM_RAW_001 schema
ALTER TASK CRM_RAW_001.ACCI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ACCOUNTS RESUME;
ALTER TASK CRM_RAW_001.ACCI_RAW_TASK_LOAD_ACCOUNTS RESUME;

-- ============================================================
-- Resume REF_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK REF_RAW_001.REFI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_FX_RATES RESUME;
ALTER TASK REF_RAW_001.REFI_RAW_TASK_LOAD_FX_RATES RESUME;

-- ============================================================
-- Resume PAY_RAW_001 Tasks (4 tasks: 2 load + 2 cleanup)
-- ============================================================
ALTER TASK PAY_RAW_001.PAYI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRANSACTIONS RESUME;
ALTER TASK PAY_RAW_001.PAYI_RAW_TASK_LOAD_TRANSACTIONS RESUME;

ALTER TASK PAY_RAW_001.ICGI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_SWIFT_MESSAGES RESUME;
ALTER TASK PAY_RAW_001.ICGI_RAW_TASK_LOAD_SWIFT_MESSAGES RESUME;

-- ============================================================
-- Resume EQT_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK EQT_RAW_001.EQTI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES RESUME;
ALTER TASK EQT_RAW_001.EQTI_RAW_TASK_LOAD_TRADES RESUME;

-- ============================================================
-- Resume FII_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK FII_RAW_001.FIII_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES RESUME;
ALTER TASK FII_RAW_001.FIII_LOAD_TRADES_TASK RESUME;

-- ============================================================
-- Resume CMD_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK CMD_RAW_001.CMDI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES RESUME;
ALTER TASK CMD_RAW_001.CMDI_LOAD_TRADES_TASK RESUME;

-- ============================================================
-- Resume LOA_RAW_001 Tasks (2 tasks: DocAI pipeline)
-- ============================================================
-- Note: Loan module uses simplified architecture with no separate load tasks
-- - Email files are uploaded directly to LOAI_RAW_STAGE_EMAIL_INBOUND
-- - Stream LOAI_RAW_STREAM_EMAIL_FILES detects new files
-- - Task LOAI_RAW_TASK_EXTRACT_MAIL_DATA extracts data with AI_EXTRACT
-- - Task LOAI_RAW_TASK_FLAT_MAIL_DATA flattens data (AFTER extraction)

-- Resume child task first (FLAT_MAIL_DATA - flattens extracted data)
ALTER TASK LOA_RAW_001.LOAI_RAW_TASK_FLAT_MAIL_DATA RESUME;

-- Resume root task last (EXTRACT_MAIL_DATA - triggers child via AFTER clause)
ALTER TASK LOA_RAW_001.LOAI_RAW_TASK_EXTRACT_MAIL_DATA RESUME;

-- ============================================================
-- Resume REP_RAW_001 Tasks (4 tasks: 2 load + 2 cleanup - FINMA LCR)
-- ============================================================
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_HQLA_HOLDINGS RESUME;
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_LOAD_HQLA_HOLDINGS RESUME;

ALTER TASK REP_RAW_001.LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_DEPOSIT_BALANCES RESUME;
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_LOAD_DEPOSIT_BALANCES RESUME;

-- ============================================================
-- COMPLETION MESSAGE
-- ============================================================
SELECT
    'DYNAMIC_RESUMPTION_COMPLETE' AS status,
    CURRENT_TIMESTAMP() AS completed_at,
    'All 71 dynamic tables and 32 tasks have been resumed.' AS message,
    'Details: 71 DTs (29 REP, 11 CRM, 6 PAY, 3 EQT, 5 FII, 5 CMD, 1 REF, 6 LCR, 5 Loan), 32 tasks (16 load + 15 cleanup + 1 customer status).' AS details,
    'System is now in operational mode. Loan DocAI pipeline active (EXTRACT task triggers FLAT_MAIL_DATA via AFTER clause).' AS next_step;