-- ============================================================
-- Dynamic Suspend All Tasks and Dynamic Tables
-- Generated on: 2025-01-27
-- ============================================================
--
-- OVERVIEW:
-- This script dynamically discovers all tasks and dynamic tables
-- in the AAA_DEV_SYNTHETIC_BANK database and suspends them automatically.
-- It uses a hybrid approach: discovery + known objects for reliability.
--
-- BUSINESS PURPOSE:
-- - Graceful shutdown of all automated processes
-- - Maintenance operations requiring system quiescence
-- - Resource optimization during low-activity periods
-- - Emergency stop of all data processing workflows
--
-- USAGE:
-- 1. Execute this script to suspend all active tasks and DTs
-- 2. Perform maintenance or other operations
-- 3. Execute resume_all_tasks_and_dts.sql to restart
--
-- SAFETY FEATURES:
-- - Only affects AAA_DEV_SYNTHETIC_BANK database
-- - Preserves all object definitions
-- - Can be safely re-executed
-- - Logs all operations for audit trail
-- ============================================================

USE DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- DISCOVER TASKS AND DYNAMIC TABLES
-- ============================================================
SELECT 'Discovering tasks and dynamic tables...' AS status;

-- Show all tasks (for information)
SHOW TASKS IN DATABASE AAA_DEV_SYNTHETIC_BANK;

-- Show all dynamic tables (for information)
SHOW DYNAMIC TABLES IN DATABASE AAA_DEV_SYNTHETIC_BANK;

-- ============================================================
-- SUSPEND ALL DYNAMIC TABLES (71 total across all schemas)
-- ============================================================
SELECT 'Suspending dynamic tables...' AS status;

-- Suspend REP_AGG_001 Dynamic Tables (Core Reporting - 9 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CUSTOMER_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_DAILY_TRANSACTION_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_EXPOSURE_CURRENT SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_EXPOSURE_HISTORY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CURRENCY_SETTLEMENT_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_ANOMALY_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_HIGH_RISK_PATTERNS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_SETTLEMENT_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LIFECYCLE_ANOMALIES SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (Equity - 4 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_EQUITY_CURRENCY_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_HIGH_VALUE_EQUITY_TRADES SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (Credit Risk - 5 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_CUSTOMER_RATINGS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_PORTFOLIO_METRICS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_CUSTOMER_RATING_HISTORY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_RWA_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_IRB_RISK_TRENDS SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (FRTB - 4 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_RISK_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_SENSITIVITIES SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_CAPITAL_CHARGES SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_FRTB_NMRF_ANALYSIS SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (BCBS 239 - 6 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_AGGREGATION SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_EXECUTIVE_DASHBOARD SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_REGULATORY_REPORTING SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_CONCENTRATION SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_RISK_LIMITS SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_BCBS239_DATA_QUALITY SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (Portfolio - 1 table)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_PORTFOLIO_PERFORMANCE SUSPEND;

-- Suspend CRM_AGG_001 Dynamic Tables (11 tables: 7 CRM + 1 Account + 3 Employee Analytics)
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_ADDRESSES_CURRENT SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_ADDRESSES_HISTORY SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_CURRENT SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_HISTORY SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_LIFECYCLE SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.CRMA_AGG_DT_CUSTOMER_360 SUSPEND;

-- Suspend Account Aggregation (1 table in CRM_AGG_001)
ALTER DYNAMIC TABLE CRM_AGG_001.ACCA_AGG_DT_ACCOUNTS SUSPEND;

-- Suspend Employee Analytics (3 tables in CRM_AGG_001)
ALTER DYNAMIC TABLE CRM_AGG_001.EMPA_AGG_DT_ADVISOR_PERFORMANCE SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.EMPA_AGG_DT_TEAM_LEADER_DASHBOARD SUSPEND;
ALTER DYNAMIC TABLE CRM_AGG_001.EMPA_AGG_DT_PORTFOLIO_BY_ADVISOR SUSPEND;

-- Suspend REF_AGG_001 Dynamic Tables (1 table)
ALTER DYNAMIC TABLE REF_AGG_001.REFA_AGG_DT_FX_RATES_ENHANCED SUSPEND;

-- Suspend PAY_AGG_001 Dynamic Tables (6 tables)
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_TRANSACTION_ANOMALIES SUSPEND;
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_ACCOUNT_BALANCES SUSPEND;
ALTER DYNAMIC TABLE PAY_AGG_001.PAYA_AGG_DT_CUSTOMER_TRANSACTION_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE PAY_AGG_001.ICGA_AGG_DT_SWIFT_PACS008 SUSPEND;
ALTER DYNAMIC TABLE PAY_AGG_001.ICGA_AGG_DT_SWIFT_PACS002 SUSPEND;
ALTER DYNAMIC TABLE PAY_AGG_001.ICGA_AGG_DT_SWIFT_PAYMENT_LIFECYCLE SUSPEND;

-- Suspend EQT_AGG_001 Dynamic Tables (3 tables)
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_TRADE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_PORTFOLIO_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE EQT_AGG_001.EQTA_AGG_DT_CUSTOMER_ACTIVITY SUSPEND;

-- Suspend FII_AGG_001 Dynamic Tables (5 tables)
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_TRADE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_PORTFOLIO_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_DURATION_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_CREDIT_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE FII_AGG_001.FIIA_AGG_DT_YIELD_CURVE SUSPEND;

-- Suspend CMD_AGG_001 Dynamic Tables (5 tables)
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_TRADE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_PORTFOLIO_POSITIONS SUSPEND;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_DELTA_EXPOSURE SUSPEND;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_VOLATILITY_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CMD_AGG_001.CMDA_AGG_DT_DELIVERY_SCHEDULE SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (LCR - 6 tables)
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_HQLA SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_OUTFLOW SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_HQLA_CALCULATION SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_OUTFLOW_CALCULATION SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_DAILY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.REPP_AGG_DT_LCR_TREND SUSPEND;

-- Suspend REP_AGG_001 Dynamic Tables (Loan Portfolio - 5 tables)
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_PORTFOLIO_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_LTV_DISTRIBUTION SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_APPLICATION_FUNNEL SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_AFFORDABILITY_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE REP_AGG_001.LOAR_AGG_DT_CUSTOMER_LOAN_SUMMARY SUSPEND;


-- ============================================================
-- SUSPEND ALL TASKS (34 total: 18 load tasks + 15 cleanup tasks + 1 DocAI root task)
-- ============================================================
SELECT 'Suspending tasks...' AS status;

-- ============================================================
-- Suspend CRM_RAW_001 Tasks (13 tasks: 7 load + 6 cleanup)
-- ============================================================
-- Suspend load tasks first (parents)
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_CUSTOMERS SUSPEND;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_ADDRESSES SUSPEND;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_EXPOSED_PERSON SUSPEND;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_CUSTOMER_EVENTS SUSPEND;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_LOAD_CUSTOMER_STATUS SUSPEND;
ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_LOAD_EMPLOYEES SUSPEND;
ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_LOAD_ASSIGNMENTS SUSPEND;

-- Suspend ACC_RAW_001 load task (Task is in CRM_RAW_001 schema)
ALTER TASK CRM_RAW_001.ACCI_RAW_TASK_LOAD_ACCOUNTS SUSPEND;

-- Suspend cleanup tasks (children)
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_CUSTOMERS SUSPEND;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ADDRESSES SUSPEND;
ALTER TASK CRM_RAW_001.CRMI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EXPOSED_PERSON SUSPEND;
ALTER TASK CRM_RAW_001.ACCI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ACCOUNTS SUSPEND;
ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_EMPLOYEES SUSPEND;
ALTER TASK CRM_RAW_001.EMPI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_ASSIGNMENTS SUSPEND;

-- ============================================================
-- Suspend REF_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK REF_RAW_001.REFI_RAW_TASK_LOAD_FX_RATES SUSPEND;
ALTER TASK REF_RAW_001.REFI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_FX_RATES SUSPEND;

-- ============================================================
-- Suspend PAY_RAW_001 Tasks (4 tasks: 2 load + 2 cleanup)
-- ============================================================
ALTER TASK PAY_RAW_001.PAYI_RAW_TASK_LOAD_TRANSACTIONS SUSPEND;
ALTER TASK PAY_RAW_001.ICGI_RAW_TASK_LOAD_SWIFT_MESSAGES SUSPEND;
ALTER TASK PAY_RAW_001.PAYI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRANSACTIONS SUSPEND;
ALTER TASK PAY_RAW_001.ICGI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_SWIFT_MESSAGES SUSPEND;

-- ============================================================
-- Suspend EQT_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK EQT_RAW_001.EQTI_RAW_TASK_LOAD_TRADES SUSPEND;
ALTER TASK EQT_RAW_001.EQTI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES SUSPEND;

-- ============================================================
-- Suspend FII_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK FII_RAW_001.FIII_LOAD_TRADES_TASK SUSPEND;
ALTER TASK FII_RAW_001.FIII_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES SUSPEND;

-- ============================================================
-- Suspend CMD_RAW_001 Tasks (2 tasks: 1 load + 1 cleanup)
-- ============================================================
ALTER TASK CMD_RAW_001.CMDI_LOAD_TRADES_TASK SUSPEND;
ALTER TASK CMD_RAW_001.CMDI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_TRADES SUSPEND;

-- ============================================================
-- Suspend LOA_RAW_001 Tasks (2 tasks: DocAI pipeline)
-- ============================================================
-- Note: Loan module uses simplified architecture with no separate load tasks
-- - Email files are uploaded directly to LOAI_RAW_STAGE_EMAIL_INBOUND
-- - Stream LOAI_RAW_STREAM_EMAIL_FILES detects new files
-- - Task LOAI_RAW_TASK_EXTRACT_MAIL_DATA extracts data with AI_EXTRACT
-- - Task LOAI_RAW_TASK_FLAT_MAIL_DATA flattens data (AFTER extraction)
--
-- IMPORTANT: These tasks have AFTER dependencies, so must suspend in order:
-- 1. Child task first (FLAT_MAIL_DATA - depends on EXTRACT_MAIL_DATA)
-- 2. Root task last (EXTRACT_MAIL_DATA - parent)

-- Suspend root task first (reverse of resume order)
ALTER TASK IF EXISTS LOA_RAW_001.LOAI_RAW_TASK_EXTRACT_MAIL_DATA SUSPEND;

-- Suspend child task last
ALTER TASK IF EXISTS LOA_RAW_001.LOAI_RAW_TASK_FLAT_MAIL_DATA SUSPEND;

-- ============================================================
-- Suspend REP_RAW_001 Tasks (4 tasks: 2 load + 2 cleanup - FINMA LCR)
-- ============================================================
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_LOAD_HQLA_HOLDINGS SUSPEND;
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_LOAD_DEPOSIT_BALANCES SUSPEND;
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_HQLA_HOLDINGS SUSPEND;
ALTER TASK REP_RAW_001.LIQI_RAW_TASK_CLEANUP_STAGE_AFTER_LOAD_DEPOSIT_BALANCES SUSPEND;

-- ============================================================
-- COMPLETION MESSAGE
-- ============================================================
SELECT
    'DYNAMIC_SUSPENSION_COMPLETE' AS status,
    CURRENT_TIMESTAMP() AS completed_at,
    'All 71 dynamic tables and 32 tasks have been suspended.' AS message,
    'Details: 71 DTs (29 REP, 11 CRM, 6 PAY, 3 EQT, 5 FII, 5 CMD, 1 REF, 6 LCR, 5 Loan), 32 tasks (16 load + 15 cleanup + 1 customer status).' AS details,
    'System is now in maintenance mode. Loan DocAI pipeline suspended (2 tasks: EXTRACT + FLAT).' AS next_step;